Repository bobby1343/helloworld, pull requests merged in 2022-10, with the labels that each got.

#4 Create javascript.js
  javascript.js
Labels: hacktoberfest-accepted

#5 Create python.py
  python.py
Labels: hacktoberfest-accepted

#6 Add C++
  c++.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#13 Hello World in php
  php.php
Labels: hacktoberfest, hacktoberfest-accepted

#12 Hello World in swift
  swift.swift
Labels: hacktoberfest, hacktoberfest-accepted

#11 Hello World in java added
  Java.java
Labels: hacktoberfest, hacktoberfest-accepted

#10 Create go.go
  go.go
Labels: hacktoberfest, hacktoberfest-accepted

#9 Create dart.dart
  dart.dart
Labels: hacktoberfest, hacktoberfest-accepted

#14 Create helloworld.java
  helloworld.java
Labels: hacktoberfest, hacktoberfest-accepted

#7 Add C
  c.c
Labels: hacktoberfest, hacktoberfest-accepted

#8 Add C sharp
  cs.cs
Labels: hacktoberfest, hacktoberfest-accepted

#15 Create Hello World.go in Golang
  Hello World.go
Labels: hacktoberfest, hacktoberfest-accepted

#24 Create HelloWorld.pas
  HelloWorld.pas
Labels: hacktoberfest, hacktoberfest-accepted

#23 Added HelloWorld program in Kotlin
  Kotlin.kt
Labels: hacktoberfest, hacktoberfest-accepted

#22 Create helloworld.sql
  helloworld.sql
Labels: help wanted, hacktoberfest-accepted

#21 Create helloworld.r
  helloworld.r
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#20 Create Ruby.rb
  Ruby.rb
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#17 kotlin file added
  kotlin.kt
Labels: hacktoberfest, hacktoberfest-accepted

#19 Create HelloWorld.go
  HelloWorld.go
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#16 Create html.html
  html.html
Labels: hacktoberfest, hacktoberfest-accepted

#27 Create helloworld.fs
  helloworld.fs
Labels: hacktoberfest, hacktoberfest-accepted

#29 Hello World in Shell Script
  shell.sh
Labels: hacktoberfest, hacktoberfest-accepted

#26 Create helloworld.matlab
  helloworld.matlab
Labels: hacktoberfest-accepted

#28 HelloWorld in Rust and Scala
  hello.rs
  hello.scala
Labels: hacktoberfest, hacktoberfest-accepted

#31 Code refactor
  Hello World.go
  HelloWorld.go
  R.r
  c.c
  fs.fs
  go.go
  java.java
  kotlin.kt
  matlab.matlab
  pas.pas
  rust.rs
  scala.scala
  sql.sql
Labels: hacktoberfest, hacktoberfest-accepted

#32 add info to Readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#33 Create intercal.i
  intercal.i
Labels: hacktoberfest-accepted

#38 Create autoit.au3
  autoit.au3
Labels: hacktoberfest-accepted

#37 Create groovy.groovy
  groovy.groovy
Labels: hacktoberfest, hacktoberfest-accepted

#36 Create batch.bat
  batch.bat
Labels: hacktoberfest, hacktoberfest-accepted
